### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by oolongmoon** [stoufferlab/pymfinder#32]
Hello!

I faced some problem when I want to import the pymfinder in jupyter notebook. However, I passed test before. I don't know how to solve it. Here is the error detail:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_72274/4163426609.py in <module>
      5 from pandas import Series,DataFrame
      6 import statistics
----> 7 import pymfinder as py

~/.local/lib/python3.8/site-packages/pymfinder-1.0-py3.8-linux-x86_64.egg/pymfinder/__init__.py in <module>
     11 	]
     12 
---> 13 from pymfinder import list_motifs, print_motifs
     14 from pymfinder import random_network
     15 from pymfinder import motif_structure

ImportError: cannot import name 'list_motifs' from partially initialized module 'pymfinder' (most likely due to a circular import) (/home/oolongmoon/.local/lib/python3.8/site-packages/pymfinder-1.0-py3.8-linux-x86_64.egg/pymfinder/__init__.py)

Thank you for any helps!

**Comment by bernibra** [comment]
It could be that you are trying to import the module from inside the repository.  Try starting the notebook from another directory.

**Comment by oolongmoon** [comment]
> It could be that you are trying to import the module from inside the repository. Try starting the notebook from another directory.

I downloaded the python 3 branch file and re-install it, then it's solved.
