### ISSUE TITLE
Visualizing Motifs from Pymfinder Output

### ISSUE THREAD

**Issue by Rohak72** [stoufferlab/pymfinder#34]
Hello,

Is there a way to use the pymfinder output as input to downstream analyses that visualize the motifs themselves? How should the raw motif data be explored and what are some common methods of performing such analysis?

Thanks.

**Comment by bernibra** [comment]
There is nothing specifically designed for `pymfinder`, but with the help of the (documentation)[https://github.com/stoufferlab/pymfinder/blob/master/documentation/pymfinder_manual.pdf] and (`NetworkX`)[https://networkx.org/] you should be able to visualize anything you need.
